# Generated by Django 2.2.3 on 2019-11-09 07:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FittingRoom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saved_Models',
            new_name='Saved_Model',
        ),
    ]
