# Generated by Django 2.2.3 on 2019-11-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FittingRoom', '0002_auto_20191109_0726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saved_Model',
        ),
    ]
